add wrap_func, stop, reset, metrics and minor changes
viciious/tarantool-graphite pull request #2
Opened 2016-09-27 15:08 UTC by zlobspb

add graphite.wrap_func which adds avg, min, max, rpm stat to function with one line

add functions:
graphite.stop
graphite.reset
graphite.metrics

local added for nt variable

forgotten logging removed

2016-09-27 20:52 UTC, viciious requested changes

2016-09-27 20:52 UTC, viciious commented on graphite.lua
> +_M.reset = function()
The semantics (the fact that stop() is also called) of this function is unclear from its naming. I'd rather prefer to have an optional argument passed to stop() instead.

2016-09-27 20:52 UTC, viciious commented on graphite.lua
> +local function stat_tail(stat_name, start_time, ...)
Why "stat_tail"?..

2016-09-27 20:52 UTC, viciious commented on graphite.lua
> +_M.wrap_func = function(name, func)
Again, the semantics of this function is unclear from its naming.

2016-09-27 20:52 UTC, viciious commented on README.md
> +-- graphite.wrap_func adds for function dostuff following stats with one line:
Please rephrase this to something like "An utility function, handy for adding the following set of metrics with a single line of code".
Why this particular set anyway?  How many custom rpm metrics do you have?

2016-09-28 09:21 UTC, zlobspb commented on graphite.lua
> +_M.reset = function()
will do it

2016-09-28 09:22 UTC, zlobspb commented on graphite.lua
> +local function stat_tail(stat_name, start_time, ...)
wrap_func_with_stat_tail - ok?

2016-09-28 09:22 UTC, zlobspb commented on graphite.lua
> +_M.wrap_func = function(name, func)
maybe wrap_func_with_stat? can you suggest enything?

2016-09-28 09:35 UTC, zlobspb commented on README.md
> +-- graphite.wrap_func adds for function dostuff following stats with one line:
It's just I'm using this set. Do you want to add anything?

### Utility functions
``` lua
-- handy wrapper to add func_name_avg, func_name_min, func_name_max, func_name_rpm metrics to your function with a single line of code
graphite.wrap_func_with_stat(name, func)
```

## Usage examples
local function dostuff()
end

dostuff = graphite.wrap_func('dostuff', dostuff)
```

2016-09-29 10:02 UTC, closed without merging